### ISSUE TITLE
Python stops working when "Find Events" pushed (Windows)

### ISSUE THREAD

**Issue by kimventa** [parkin/pypore#14]
![issue](https://cloud.githubusercontent.com/assets/7173491/2684054/a04bc7a2-c1b2-11e3-97a0-ac0d5f6c81ab.png)

On Windows 7 64-bit (seemed important), Python stops working with a filtered .h5 file loaded when "Find Events" is pushed.

**Comment by guddulrk** [comment]
Hi,
I am getting following error on Windows 7 with Python 3.5 and Tensorflow 1.4. 

Problem Event Name: BEX64
  Application Name: pythonw.exe
  Application Version:  3.5.2150.1013
  Application Timestamp:    577be341
  Fault Module Name:    StackHash_1dc2
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp:   00000000
  Exception Offset: 0000000000000000
  Exception Code:   c0000005
  Exception Data:   0000000000000008
  OS Version:   6.1.7601.2.1.0.256.4
  Locale ID:    3081
  Additional Information 1: 1dc2
  Additional Information 2: 1dc22fb1de37d348f27e54dbb5278e7d
  Additional Information 3: eae3
  Additional Information 4: eae36a4b5ffb27c9d33117f4125a75c2

Can you please help me with its solution?
Thanks
